/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homework6;


import client.Client;
import client.ClientService;
import services.Database;
import services.DatabaseInitService;

import java.sql.Connection;
import java.sql.SQLException;


public class App {

    public static void main(String[] args) throws SQLException {

        Database database = Database.getInstance();
        new DatabaseInitService().initDb();
        ClientService clientService = new ClientService(database.getConnection());
        System.out.println(clientService.getById(1));
        System.out.println(clientService.listAll());

    }
}
